import type { Report, CheckResult } from '../types.js';

export function generateMarkdownReport(report: Report): string {
  const lines: string[] = [];
  const timestamp = new Date(report.timestamp).toLocaleString('en-GB', { timeZone: 'Europe/Brussels' });

  lines.push(`# Hercules Health Check Report`);
  lines.push(`**Date:** ${timestamp} (Brussels time)`);
  lines.push(`**Mode:** ${report.mode === 'daily' ? 'Daily (all sites)' : 'Post-deploy'}`);
  lines.push(`**Sites checked:** ${report.sites.join(', ').toUpperCase()}`);
  lines.push('');

  // Summary
  const failIcon = report.failed > 0 ? '🔴' : '🟢';
  lines.push(`## Summary ${failIcon}`);
  lines.push(`| Metric | Count |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total checks | ${report.totalChecks} |`);
  lines.push(`| ✅ Passed | ${report.passed} |`);
  lines.push(`| ❌ Failed | ${report.failed} |`);
  lines.push(`| ⚠️ Warnings | ${report.warnings} |`);
  lines.push('');

  if (report.failed > 0) {
    lines.push(`## ❌ Failures (Action Required)`);
    lines.push('');
    const failures = report.results.filter(r => r.status === 'fail');
    for (const f of failures) {
      lines.push(`- **[${f.site.toUpperCase()}] ${f.category} > ${f.name}**`);
      lines.push(`  ${f.message}${f.details ? ` — ${f.details}` : ''}`);
    }
    lines.push('');
  }

  if (report.warnings > 0) {
    lines.push(`## ⚠️ Warnings`);
    lines.push('');
    const warnings = report.results.filter(r => r.status === 'warn');
    for (const w of warnings) {
      lines.push(`- [${w.site.toUpperCase()}] ${w.category} > ${w.name}: ${w.message}`);
    }
    lines.push('');
  }

  // Full checklist per site
  const bySite = new Map<string, CheckResult[]>();
  for (const r of report.results) {
    if (!bySite.has(r.site)) bySite.set(r.site, []);
    bySite.get(r.site)!.push(r);
  }

  for (const [siteId, checks] of bySite) {
    lines.push(`---`);
    lines.push(`## ${siteId.toUpperCase()} — Full Checklist`);
    lines.push('');

    const byCat = new Map<string, CheckResult[]>();
    for (const c of checks) {
      if (!byCat.has(c.category)) byCat.set(c.category, []);
      byCat.get(c.category)!.push(c);
    }

    for (const [cat, catChecks] of byCat) {
      lines.push(`### ${cat}`);
      lines.push('');
      for (const c of catChecks) {
        const icon = c.status === 'pass' ? '✅' : c.status === 'fail' ? '❌' : '⚠️';
        const timeStr = c.responseTime ? ` (${c.responseTime}ms)` : '';
        lines.push(`- ${icon} ${c.name}: ${c.message}${timeStr}`);
        if (c.status === 'fail' && c.details) {
          lines.push(`  > ${c.details}`);
        }
      }
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('*Generated by Hercules Health Check Agent*');

  return lines.join('\n');
}

export function generateHtmlReport(report: Report): string {
  const md = generateMarkdownReport(report);
  const timestamp = new Date(report.timestamp).toLocaleString('en-GB', { timeZone: 'Europe/Brussels' });

  // Simple HTML conversion
  let html = md
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/^- ✅ (.+)$/gm, '<div style="color:#16a34a;margin:2px 0;">✅ $1</div>')
    .replace(/^- ❌ (.+)$/gm, '<div style="color:#dc2626;margin:2px 0;font-weight:bold;">❌ $1</div>')
    .replace(/^- ⚠️ (.+)$/gm, '<div style="color:#d97706;margin:2px 0;">⚠️ $1</div>')
    .replace(/^- (.+)$/gm, '<div style="margin:2px 0;">• $1</div>')
    .replace(/^  > (.+)$/gm, '<div style="margin-left:20px;color:#666;font-size:12px;">↳ $1</div>')
    .replace(/^\|(.+)\|$/gm, (match) => {
      const cells = match.split('|').filter(Boolean).map(c => c.trim());
      if (cells.every(c => c.match(/^-+$/))) return '';
      const tag = cells[0] === 'Metric' ? 'th' : 'td';
      return `<tr>${cells.map(c => `<${tag} style="padding:4px 12px;border:1px solid #ddd;">${c}</${tag}>`).join('')}</tr>`;
    })
    .replace(/^---$/gm, '<hr>')
    .replace(/\n\n/g, '<br>');

  // Wrap table rows
  html = html.replace(/(<tr>[\s\S]*?<\/tr>)/g, '<table style="border-collapse:collapse;margin:8px 0;">$1</table>');

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:900px;margin:20px auto;padding:0 20px;font-size:14px;line-height:1.5;color:#333;}
h1{color:#253461;} h2{color:#253461;margin-top:24px;} h3{color:#469ADC;margin-top:16px;}
hr{border:none;border-top:2px solid #eee;margin:20px 0;}
</style></head><body>${html}</body></html>`;
}

export function getSubjectLine(report: Report): string {
  if (report.failed > 0) {
    return `🔴 Hercules Health Check: ${report.failed} FAILURES — ${report.sites.map(s => s.toUpperCase()).join(', ')}`;
  }
  if (report.warnings > 5) {
    return `⚠️ Hercules Health Check: ${report.warnings} warnings — ${report.sites.map(s => s.toUpperCase()).join(', ')}`;
  }
  return `✅ Hercules Health Check: All ${report.totalChecks} checks passed — ${report.sites.map(s => s.toUpperCase()).join(', ')}`;
}
